name: frontend
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  # flutter_unity_widget: ^2022.2.1 -> Flutter 3.24 breaks API to class in flutter_unity_widget so it causes kotlin compilation errors
  flutter_unity_widget:
    git:
      url: https://github.com/juicycleff/flutter-unity-view-widget.git
      ref: flutter_3.24_android_hotfix # branch name
  conditional_parent_widget: ^0.0.2
  pointer_interceptor: ^0.10.1+2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env/
